Update "make depends" to generate direct rules for builtins/*.def -> *.o

diff --git a/support/mkdep b/support/mkdep
--- a/support/mkdep
+++ b/support/mkdep
@@ -29,13 +29,13 @@ blddir=.
 compiler=cc
 debug=false
 depfile=.depend
-keep_output=false
-keep_output_on_error=false
+keep_temps=false
+keep_temps_on_error=false
 keep_path=false
-m_flag=-MM
+unset m_flag
 patch_makefile=
-skip_o=false
 presort_depfile=true
+rewrite_list=
 sort_depfile=false
 srcdir=
 topdir=
@@ -59,22 +59,96 @@ die()
   case $1 in EX_*) ex=2 ; shift ;; [0-9]*) ex=$1 ; shift ; esac
   echo "$PROG: $*"
   exit $ex
-}
+} >&2
 
-usage()
+show_usage()
 {
-  echo "$PROG: usage: $PROG [-a] [-c compiler] [-f depend_file] [-k f|ff|p] [-m M|MM] [-p] [-P|--patch=[Makefile]] [-S SRCDIR] [-T SRCTOP] [--] [cc_flags] file ..." >&2
+  cat <<EndOfHelp
+Usage: $PROG [OPTIONS] [-- [COMPILER_FLAGS...]] FILES...
+
+Options:
+
+  --append,
+  -a		append to dependency file
+
+  --compiler=COMPILER,
+  -c COMPILER	change compiler (default: gcc)
+
+  --exclude=PATH,
+  -e PATH	add to exclusion path list
+
+  --dep-file=FILE,
+  -f FILE	use dependency file (default: .depend)
+
+  --keep-errors,
+  -ke		keep temp files if an error occurs
+
+  --keep-temps,
+  -kt		keep temp files
+
+  --keep-path,
+  -kp		keep PATH from environment
+
+  -M		pass -M compiler (don't exclude system includes)
+  -m       	pass -MM to compiler (default with gcc or clang)
+
+  -p		shorthand for '-r %.o=%'
+
+  --patch=[Makefile],
+  -P		incorporate dependency file into Makefile
+
+  --srcdir=SRCDIR,
+  -S SRCDIR
+
+  --topdir=TOP_SRCDIR
+  -T TOP_SRCDIR
+
+  -r REPLACEMENT-RULE (for sources)
+  -R REPLACEMENT-RULE (for targets)
+
+Replacement rules can be:
+  FROM_PATH%FROM_SUFFIX=TO_PATH%TO_SUFFIX
+		("%" matches a file not in a subdirectory)
+
+  s@PATTERN@REPLACEMENT@
+		(can use '@' or '%' or '#'; avoid '/')
+EndOfHelp
   exit 0
 }
 
-bad_usage()
+add_replacement ()
 {
-  echo "$PROG: usage: $PROG [-a] [-c compiler] [-f depend_file] [-k f|ff|p] [-m M|MM] [-p] [-P|--patch=[Makefile]] [-S SRCDIR] [-T SRCTOP] [--] [cc_flags] file ..." >&2
-  exit 2
+  rep=$1 how=$2
+  case $1 in
+
+    *%*=*%*)
+	    # With a wildcard
+	    fr=${OPTARG%=*%*}  fp=${fr%'%'*} fs=${fr#"$fp%"}
+	    to=${OPTARG#"$fr="} tp=${to%'%'*} ts=${to#"$tp%"}
+	    case $2 in
+	      s*) fp=' '$fp tp=' '$tp fs=$fs'$' ;;
+	      t*) fp='^'$fp fs=$fs': '  ;;
+	    esac
+	    rewrite_list="$rewrite_list$NL s#$fp\([^/: ]*\)$fs#$tp\1$ts# ;" ;;
+
+    *=*)
+	    # Without a wildcard
+	    fr=${OPTARG%=*}
+	    to=${OPTARG#"$fr="}
+	    case $2 in
+	      s*) fr=' '$fr'$' to=' '$to ;;
+	      t*) fr='^'$fr': '  ;;
+	    esac
+	    rewrite_list="$rewrite_list$NL s#$fr#$to# ;" ;;
+
+    s#*#*#)	rewrite_list="$rewrite_list$NL $OPTARG ;" ;;
+    s@*@*@)	rewrite_list="$rewrite_list$NL $OPTARG ;" ;;
+    s%*%*%)	rewrite_list="$rewrite_list$NL $OPTARG ;" ;;
+    *)	die EX_USAGE "Invalid replacement pattern '$OPTARG'; type '$PROG --help' for more" ;;
+  esac
 }
 
-
-while getopts ac:f:k:m:psDPS:T:-: opt "$@"
+while getopts ac:Df:k:mMpPr:R:sS:T:-: opt "$@"
 do
   case $opt in
     a)
@@ -86,6 +160,9 @@ do
       compiler=$OPTARG
       ;;
 
+    D)
+      debug=true ;;
+
     e)
       # add item to the exclusion list
       exclusion_list="$exclusion_list$NL: $OPTARG"
@@ -96,47 +173,63 @@ do
       depfile=$OPTARG
       ;;
 
+    h)
+      show_usage
+      ;;
+
     k)
       case $OPTARG in
-      f)
+      e)
 	# Keep the temporary files on failure
-	keep_output_on_error=true ;;
+	keep_temps_on_error=true ;;
 
-      ff)
+      t)
 	# Keep the temporary files always
-	keep_output=true ;;
+	keep_temps=true ;;
 
       p)
 	# keep PATH from environment
 	keep_path=true ;;
 
-      *) bad_usage ;;
+      *) die EX_USAGE "Invalid -k suboption '$OPTARG'; type '$PROG --help' for more" ;;
       esac ;;
 
     m)
-      # report or ignore system-supplied #include files
-      case $OPTARG in
-      M | MM) m_flag=-$OPTARG ;;
-      *) bad_usage ;;
-      esac
+      # ignore system-supplied #include files
+      m_flag=-MM
+      ;;
+
+    M)
+      # include system-supplied #include files
+      m_flag=-M
       ;;
 
     p)
-      # produce “program: program.c”-style dependencies
+      # If the real target is a completed executable, create a dependency list
+      # directly targetting it, rather than the intermediate .o file(s).
+      # Produce “program: program.c”-style dependencies
       # (to avoid generating .o files)
-      skip_o=true ;;
+      rewrite_list="$rewrite_list s#^\([^/]*\)\.o:#\1:# ;$NL"
+      ;;
+
+    P)
+      patch_makefile=Makefile ;;
+
+    r)
+      # Target replacement rule
+      add_replacement "$OPTARG" t
+      ;;
+
+    R)
+      # Source replacement rule
+      add_replacement "$OPTARG" s
+      ;;
 
     s)
       # re-sort whole depfile, after normalisation and merging, to prevent
       # creating duplicates
-      presort_depfile=false # no need for two sorts
+      presort_depfile=false # no need to sort twice
       sort_depfile=true ;;
-
-    D)
-      debug=true ;;
-
-    P)
-      patch_makefile=Makefile ;;
 
     S)
       srcdir=$OPTARG
@@ -147,32 +240,77 @@ do
       ;;
 
     -)
-      LONGOPT=${OPTARG%%=*}
-      OPTVAL=${OPTARG#"$LONGOPT"}
-      case $OPTVAL in '') unset OPTVAL ;; *) OPTVAL=${OPTVAR#=} ; esac
-      case $LONGOPT in
-	n*p*)
-	    case nopatch	in "$LONGOPT"*) patch_makefile= ; continue ; esac
-	    case no-patch	in "$LONGOPT"*) patch_makefile= ; continue ; esac ;;
-	p*) case patch-makefile	in "$LONGOPT"*) patch_makefile=${OPTVAL-Makefile} ; continue ; esac ;;
-	s*) case srcdir		in "$LONGOPT"*) srcdir=${OPTVAL} ; continue ; esac
-	    case srctop		in "$LONGOPT"*) topdir=${OPTVAL} ; continue ; esac
-	    ;;
-	t*) case topdir		in "$LONGOPT"*) topdir=${OPTVAL} ; continue ; esac ;;
+      opt=${OPTARG%%=*}
+      arg=${OPTARG#"$opt"}
+      case $arg in '') unset arg ;; *) arg=${arg#=} ; esac
+      hopt=${opt%%-*}
+      case $opt in
+	ap*)	case append		in "$opt"*) append_depfile=true ; continue ; esac ;;
+	cc)					    compiler=$arg ; continue ;;
+	co*)	case compiler		in "$opt"*) compiler=$arg ; continue ; esac ;;
+	de*-f*)	case dependency		in "$hopt"*)
+		  opt=${opt#*-}
+		  case file		in "$opt"*) depfile=$arg ; continue ; esac ;;
+		esac ;;
+	exc*)	case exclude		in "$opt"*) exclusion_list="$exclusion_list$NL: $arg" ; continue ; esac ;;
+	h*)	case help		in "$opt"*) show_usage ; esac ;;
+	k*-*)	case keep		in "$hopt"*)
+		  opt=${opt#*-}
+		  case $opt in
+		    e*)	case errors	in "$opt"*) keep_temps=false keep_temps_on_error=true ; continue ; esac ;;
+		    p*)	case path	in "$opt"*) keep_path=true ; continue ; esac ;;
+		    t*)	case temps	in "$opt"*) keep_temps=true keep_temps_on_error=true ; continue ; esac ;;
+		  esac
+		esac ;;
+	n*-*)
+		case no	in "$hopt"*)
+		  opt=${opt#*-}
+		  hopt=${opt%%-*}
+		  case $opt in
+		    k*-*)
+		      case keep		in "$hopt"*)
+			opt=${opt#*-}
+			case $opt in
+			p*) case path	in "$opt"*) keep_path=false ; continue ; esac ;;
+			t*) case temps	in "$opt"*) keep_temps=true keep_temps_on_error=false ; continue ; esac ;;
+			esac
+		      esac ;;
+		    p*)	case patch	in "$opt"*) patch_makefile= ; continue ; esac
+		  esac
+		esac ;;
+	p*)	case patch-makefile	in "$opt"*) patch_makefile=${arg-Makefile} ; continue ; esac ;;
+	r*-s*)	case replace		in "$hopt"*)
+		  opt=${opt#*-}
+		  case source		in "$opt"*) add_replacement "$arg" s ; continue ; esac
+		  case src		in "$opt"*) add_replacement "$arg" s ; continue ; esac
+		esac ;;
+	r*-t*)	case replace		in "$hopt"*)
+		  opt=${opt#*-}
+		  case target		in "$opt"*) add_replacement "$arg" t ; continue ; esac
+		  case tgt		in "$opt"*) add_replacement $arg t ; continue ; esac
+		esac ;;
+	s*d*)	case srcdir		in "$opt"*) srcdir=$arg ; continue ; esac ;;
+	s*t*)	case srctop		in "$opt"*) topdir=$arg ; continue ; esac ;;
+	t*)	case topdir		in "$opt"*) topdir=$arg ; continue ; esac ;;
+	u*)	case usage		in "$opt"*) show_usage ; esac ;;
       esac
-      bad_usage ;;
+      die EX_USAGE "Invalid or ambiguous option '--$opt'; type '$PROG --help' for more" ;;
 
     ?)
-      bad_usage ;;
+      die EX_USAGE "Invalid option '-$opt'; type '$PROG --help' for more" ;;
   esac
 
 done
 
 shift $(( $OPTIND - 1 ))
 
-if [ $# = 0 ] ; then
-  usage
-fi
+[ $# != 0 ] ||
+  die EX_USAGE 'At least one source file required'
+
+case ${compiler##*/} in
+ gcc* | clang*) _=${m_flag=-MM} ;;
+             *) _=${m_flag=-M} ;;
+esac
 
 exclusion_list=${exclusion_list#"$NL"}
 
@@ -361,12 +499,12 @@ cleanup()
   :
 }
 
-if "$keep_output"
+if "$keep_temps"
 then end_cleanup() { :; }
 else end_cleanup() { cleanup ; }
 fi
 
-if "$keep_output_on_error"
+if "$keep_temps_on_error"
 then soft_cleanup() { :; }
 else soft_cleanup() { cleanup ; }
 fi
@@ -416,28 +554,31 @@ sed '
       D
       tb
     }
-  ' < "$output.1" > "$output.2" || die 'Unrolling failed'
+  ' < "$output.1" > "$output.2" ||
+  die 'Unrolling failed'
+
+# Custom rewriting
+
+sed < "$output.2" > "$output.3" "
+    $rewrite_list
+    s#\$(srcdir)#$srcdir#g;
+    s#\$(topdir)#$topdir#g;
+" ||
+  die 'Path rewriting failed'
+
+# Apply exclusion list
 
 if test -n "$exclusion_list"
 then
-  grep -vF "$exclusion_list"  < "$output.2" > "$output.3"
-else
-  ln "$output.2" "$output.3"
-fi || die 'Filtering failed'
-
-# If the real target is a completed executable, create a dependency list
-# directly targetting it, rather than the intermediate .o file(s).
-
-if "$skip_o"
-then
-  sed 's@\.o: @: @' < "$output.3" > "$output.4"
+  grep -vF "$exclusion_list"  < "$output.3" > "$output.4"
 else
   ln "$output.3" "$output.4"
-fi || die 'Executable trimming failed'
+fi ||
+  die 'Filtering failed'
 
 # Canonicalize paths changing A/B/C/../../D to A/D
 
-sed '
+sed < "$output.4" > "$output.5" '
     :a
     s@^\./@@
     s@ \./@ @g
@@ -448,7 +589,8 @@ sed '
     s@ [^/. ][^/ ]*/\.\./@ @g
     s@/[^/. ][^/ ]*/\.\./@/@g
     tb
-  ' < "$output.4" > "$output.5" || die 'Path normalization failed'
+' ||
+  die 'Path normalization failed'
 
 # Sort the generated dependency list to eliminate duplicates
 
@@ -457,7 +599,8 @@ then
   sort -u "$output.5" > "$output.6"
 else
   ln "$output.5" "$output.6"
-fi || die 'Pre-sorting failed'
+fi ||
+  die 'Pre-sorting failed'
 
 # Optionally incorporate the original depfile
 
@@ -466,11 +609,13 @@ then
   cat "$depfile" "$output.6" > "$output.7"
 else
   ln "$output.6" "$output.7"
-fi || die 'Concatenation failed'
+fi ||
+  die 'Concatenation failed'
 
 # Rewrite paths as needed
 
-rewrite < "$output.7" > "$output.8" || die 'Rewriting failed'
+rewrite < "$output.7" > "$output.8" ||
+  die 'Rewriting failed'
 
 # Sort the entire output (this only makes a difference if incorporating the
 # original depfile rather than overwriting it.
@@ -480,11 +625,13 @@ then
   sort -u "$output.8" > "$output.9"
 else
   ln "$output.8" "$output.9"
-fi || die 'Sorting failed'
+fi ||
+  die 'Sorting failed'
 
 # If everything has worked, replace the depfile
 
-mv "$output.9" "$depfile" || die 'Installation failed'
+mv "$output.9" "$depfile" ||
+  die 'Installation failed'
 
 # And then if requested, apply the patches to the Makefile
 
@@ -497,7 +644,8 @@ then
     cat "$depfile"
   } > "$pmt" &&
   mv "$pmt" "$patch_makefile"
-fi || die 'Patching failed'
+fi ||
+  die 'Patching failed'
 
 end_cleanup
 
