Major rework of support/mkdep

diff --git a/support/mkdep b/support/mkdep
--- a/support/mkdep
+++ b/support/mkdep
@@ -30,10 +30,12 @@ compiler=cc
 debug=false
 depfile=.depend
 keep_output=false
+keep_output_on_error=false
 keep_path=false
 m_flag=-MM
 patch_makefile=
 skip_o=false
+presort_depfile=true
 sort_depfile=false
 srcdir=
 topdir=
@@ -51,9 +53,23 @@ NL='
 
 PROG=${0##*/}
 
+die()
+{
+  ex=$?
+  case $1 in EX_*) ex=2 ; shift ;; [0-9]*) ex=$1 ; shift ; esac
+  echo "$PROG: $*"
+  exit $ex
+}
+
 usage()
 {
-  echo "$PROG: usage: $PROG [-a] [-c compiler] [-f depend_file] [-k f|p] [-m M|MM] [-p] [-P|--patch=[Makefile]] [-S SRCDIR] [-T SRCTOP] [--] [cc_flags] file ..." >&2
+  echo "$PROG: usage: $PROG [-a] [-c compiler] [-f depend_file] [-k f|ff|p] [-m M|MM] [-p] [-P|--patch=[Makefile]] [-S SRCDIR] [-T SRCTOP] [--] [cc_flags] file ..." >&2
+  exit 0
+}
+
+bad_usage()
+{
+  echo "$PROG: usage: $PROG [-a] [-c compiler] [-f depend_file] [-k f|ff|p] [-m M|MM] [-p] [-P|--patch=[Makefile]] [-S SRCDIR] [-T SRCTOP] [--] [cc_flags] file ..." >&2
   exit 2
 }
 
@@ -67,7 +83,8 @@ do
 
     c)
       # change compiler
-      compiler=$OPTARG ;;
+      compiler=$OPTARG
+      ;;
 
     e)
       # add item to the exclusion list
@@ -76,44 +93,58 @@ do
 
     f)
       # select a dependency file
-      depfile=$OPTARG ;;
+      depfile=$OPTARG
+      ;;
 
     k)
       case $OPTARG in
-      f)  # Keep the temporary files on failure
-	  keep_output=true ;;
-      p)  # keep PATH from environment
-	  keep_path=true ;;
-      *) usage ;;
+      f)
+	# Keep the temporary files on failure
+	keep_output_on_error=true ;;
+
+      ff)
+	# Keep the temporary files always
+	keep_output=true ;;
+
+      p)
+	# keep PATH from environment
+	keep_path=true ;;
+
+      *) bad_usage ;;
       esac ;;
 
     m)
       # report or ignore system-supplied #include files
       case $OPTARG in
       M | MM) m_flag=-$OPTARG ;;
-      *) usage ;;
-      esac ;;
+      *) bad_usage ;;
+      esac
+      ;;
 
     p)
       # produce “program: program.c”-style dependencies
       # (to avoid generating .o files)
       skip_o=true ;;
 
-    D) debug=true ;;
-
     s)
-      # "sort" after rewriting, to prevent creating duplicates
-      sort_depfile=true
-      ;;
+      # re-sort whole depfile, after normalisation and merging, to prevent
+      # creating duplicates
+      presort_depfile=false # no need for two sorts
+      sort_depfile=true ;;
+
+    D)
+      debug=true ;;
 
     P)
       patch_makefile=Makefile ;;
 
     S)
-      srcdir=$OPTARG ;;
+      srcdir=$OPTARG
+      ;;
 
     T)
-      topdir=$OPTARG ;;
+      topdir=$OPTARG
+      ;;
 
     -)
       LONGOPT=${OPTARG%%=*}
@@ -129,10 +160,10 @@ do
 	    ;;
 	t*) case topdir		in "$LONGOPT"*) topdir=${OPTVAL} ; continue ; esac ;;
       esac
-      usage ;;
+      bad_usage ;;
 
     ?)
-      usage ;;
+      bad_usage ;;
   esac
 
 done
@@ -143,31 +174,184 @@ if [ $# = 0 ] ; then
   usage
 fi
 
+exclusion_list=${exclusion_list#"$NL"}
+
 "$debug" && set -x
 
-srcdir=${srcdir:+${srcdir%/}/}  # append a slash if non-empty and doesn't already end with one
-topdir=${topdir:+${topdir%/}/}  # append a slash if non-empty and doesn't already end with one
-blddir=${blddir:+${blddir%/}/}  # append a slash if non-empty and doesn't already end with one
-xtopdir=${topdir:+'$(topdir)'/}
+#
+# There are 4 directories of interest
+#   $blddir - the top of the target tree
+#   $tgtdir - the target directory (within the target tree)
+#   $topdir - the top of the source tree
+#   $srcdir - the source directory (within the source tree) that corresponds to the target directory
+# Which is to say, the relative paths from $topdir to $srcdir and from $blddir
+# to $tgtdir must be the same. Moreover, $tgtdir must be $PWD (or '.'), because
+# otherwise the paths produced by 'gcc -MM' will be wrong.
 
-_=${srcdir:=$topdir}
+# For each given path, make sure it ends with a slash (or is empty)
+srcdir=${srcdir:+${srcdir%/}/}
+topdir=${topdir:+${topdir%/}/}
+blddir=${blddir:+${blddir%/}/}
 
-rsrcdir=$( realpath "$srcdir" )/
-rtopdir=$( realpath "$topdir" )/
+# Force paths to be empty rather than ./
+srcdir=${srcdir#./}
+topdir=${topdir#./}
+blddir=${blddir#./}
 
-case $rsrcdir in
-  "$rtopdir"*) ;;
-  *)	    echo >&2 "mkdep: src_dir (-S $rsrcdir) is not within top_dir (-T $rtopdir)" ; exit 2
-esac
+# Minimize all paths:
+#   - where a path is relative, leave it as-is
+#   - if a path is a subdir of $PWD, strip the leading $PWD/
+#   - if a path is a parent dir of $PWD, convert it to a chain of '../'
+#   - all paths have a trailing '/' (unless it's empty, meaning $PWD); avoid './'
+#   - set blddir to some repetition of '../'
+#   - where a path is absolute and neither
+#
+# Various cases to cope with:
+#       topdir                  srcdir                  subdir  blddir  tgtdir
+#       [./]                    [./]                    [./]    [./]    [./]            when building in the source tree
+#       ../                     [./]                    sub/    ../     [./]
+#       ../../                  [./]                    s1/s2/  ../../  [./]
+#
+#       /abs/path/              /abs/path/              [./]    [./]    [./]            when building at an independent path
+#       /abs/path/              /abs/path/sub/          sub/    ../     [./]
+#       /abs/path/              /abs/path/s1/s2/        s1/s2/  ../../  [./]
+#
+#       (../)                   (../)                   [./]    [./]    [./]            when building in a subdir of the source tree
+#       ../(../)                ../(../)sub/            sub/    ../     [./]
+#       ../../(../)             ../../(../)s1/s2/       s1/s2/  ../../  [./]
+#
+#       (rel/)                  (rel/)                  [./]    [./]    [./]            when building in a parent directory of the source tree
+#       ../../(rel/)            ../../(rel/)s1/s2/      s1/s2/  ../../  [./]
+#
+#       (../)(rel/)             (../)(rel/)             [./]    [./]    [./]            when building beside the source tree
+#       ../(../)(rel/)          ../(../)(rel/)sub/      sub/    ../     [./]
+#       ../../(../)(rel/)       ../../(../)(rel/)s1/s2/ s1/s2/  ../../  [./]
 
-subdir=${rsrcdir#"$rtopdir"}      # where is the target dir within the build tree?
+if test -z "$srcdir"
+then
+  # Building in the source tree
+  tgtdir=
+else
 
-srcdir=${rsrcdir#"$PWD/"}
-topdir=${rtopdir#"$PWD/"}
+  # Get the relative path of the target dir within the build tree, or abort
+  subdir=${srcdir#"$topdir"}
+  case $subdir in
+    /*) die 2 " src_dir (-S $srcdir) is not within top_dir (-T $topdir)" ;;
+  esac
 
-tgtdir=$blddir$subdir
+  # Make the reverse relative path
+  # NB: this is a POSIX sh script, otherwise in Bash we could simply use:
+  #   shopt -s extglob
+  #   updir=${subdir//+([!\/])/..}
+  updir= t=/$subdir
+  while test / != "$t"
+  do
+    updir=../$updir
+    t=${t%/*/}/
+  done
 
-"$keep_path" || export PATH=/bin:/usr/bin:/usr/local/bin:/opt/bin:$PATH
+  srcdir=${srcdir#"$PWD/"}
+  topdir=${topdir#"$PWD/"}
+  blddir=${blddir#"$PWD/"}
+
+  # Verify that $tgtdir is $PWD, or die
+  tgtdir=
+
+  case $blddir$subdir in
+    '' | "$updir$subdir" | "$PWD/" )
+      blddir=$updir ;;
+
+### Should not be needed, but left here as a worked example for future use...
+#   "$subdir" | "$PWD$subdir" )
+#     blddir=
+#     tgtdir=$subdir
+#     ;;
+
+    *)
+      # Give up if we're not in the right directory:
+      # - if we don't cd, the generated target paths will be wrong;
+      # - but if we do cd, relative filenames in "$@" will be wrong;
+      die EX_UNAVAILABLE \
+	"Error: must be run from the target directory; please 'cd $tgtdir' and try again."
+      ;;
+  esac
+
+  "$keep_path" ||
+    export PATH=/bin:/usr/bin:/usr/local/bin:/opt/bin:$PATH
+
+fi
+
+rewrite_path()
+{
+  case $1 in
+    \#*) return ;;
+    \$*) echo "$1" ; return ;;
+  esac
+
+  f=${1##*/}
+  p=${1%"$f"}
+
+  case $p in
+    '' | ./ | "$PWD/" ) p= ;;
+
+    /*/)
+      common_prefix=${PWD%/}/ up2=
+      while
+	case $p in "$common_prefix"*) false ; esac &&
+	! case $common_prefix in /*/) false ; esac
+      do
+	common_prefix=${common_prefix%/*/}/
+	up2=../$up2
+      done
+      case $p in
+	"$common_prefix"*)
+	  p=$up2${p#"$common_prefix"}
+	  ;;
+      esac
+      ;;
+
+    # Handle case when PWD is /a/b/c/d and p is ../d or ../../c/d etc;
+    # You might need to add more cases if 4 isn't enough.
+    ../../../../"${PWD#"${PWD%/*/*/*/*}"}/" |\
+       ../../../"${PWD#"${PWD%/*/*/*}"}/" |\
+	  ../../"${PWD#"${PWD%/*/*}"}/" |\
+	     ../"${PWD#"${PWD%/*}"}/" )
+      p= ;;
+  esac
+
+  echo "$p$f"
+}
+
+rewrite()
+{
+  echo "# topdir=$topdir"
+  echo "# srcdir=$srcdir"
+  echo "# subdir=$subdir"
+  echo "# blddir=$blddir"
+  echo "# tgtdir=$tgtdir"
+  echo "# PWD=$PWD"
+  while
+    IFS= read -r line
+  do
+    case $line in
+      '' |\
+      '#'* |\
+      [$/]*': $'* ) echo "$line" ;;
+
+      *': $'* ) echo "$tgtdir$line" ;;
+
+      *': '*)
+	s=${line#*': '}
+	t=${line%%': '*}
+
+	echo "$tgtdir${t#./}: $( rewrite_path "$s" )"
+	;;
+      * ) echo "$line"
+	echo >&2 '# Warning: copying unmatched line: '"$line"
+	;;
+    esac
+  done
+} 2>&1
 
 output=$depfile.mkdep$$
 
@@ -178,9 +362,23 @@ cleanup()
 }
 
 if "$keep_output"
+then end_cleanup() { :; }
+else end_cleanup() { cleanup ; }
+fi
+
+if "$keep_output_on_error"
 then soft_cleanup() { :; }
 else soft_cleanup() { cleanup ; }
 fi
+
+die()
+{
+  ex=$?
+  soft_cleanup
+  case $1 in EX_*) ex=2 ; shift ;; [0-9]*) ex=$1 ; shift ; esac
+  echo "$PROG: $*"
+  exit $ex
+}
 
 caught () {
   soft_cleanup
@@ -218,14 +416,14 @@ sed '
       D
       tb
     }
-  ' < "$output.1" > "$output.2" &&
+  ' < "$output.1" > "$output.2" || die 'Unrolling failed'
 
 if test -n "$exclusion_list"
 then
-  grep -vF "${exclusion_list#$NL}"  < "$output.2" > "$output.3"
+  grep -vF "$exclusion_list"  < "$output.2" > "$output.3"
 else
   ln "$output.2" "$output.3"
-fi &&
+fi || die 'Filtering failed'
 
 # If the real target is a completed executable, create a dependency list
 # directly targetting it, rather than the intermediate .o file(s).
@@ -235,10 +433,7 @@ then
   sed 's@\.o: @: @' < "$output.3" > "$output.4"
 else
   ln "$output.3" "$output.4"
-fi &&
-
-# Canonicalize paths changing A/B/C/../../D to A/D
-
+fi || die 'Executable trimming failed'
 
 # Canonicalize paths changing A/B/C/../../D to A/D
 
@@ -253,12 +448,16 @@ sed '
     s@ [^/. ][^/ ]*/\.\./@ @g
     s@/[^/. ][^/ ]*/\.\./@/@g
     tb
-  ' < "$output.4" > "$output.5" &&
-
+  ' < "$output.4" > "$output.5" || die 'Path normalization failed'
 
 # Sort the generated dependency list to eliminate duplicates
 
-sort -u "$output.5" > "$output.6" &&
+if "$presort_depfile"
+then
+  sort -u "$output.5" > "$output.6"
+else
+  ln "$output.5" "$output.6"
+fi || die 'Pre-sorting failed'
 
 # Optionally incorporate the original depfile
 
@@ -267,54 +466,27 @@ then
   cat "$depfile" "$output.6" > "$output.7"
 else
   ln "$output.6" "$output.7"
-fi &&
-
-# Optionally sort the entire output (this only makes a difference if
-# incorporating the original depfile rather than overwriting it.
-
-if "$sort_depfile"
-then
-  sort -u "$output.7" > "$output.8"
-else
-  ln "$output.7" "$output.8"
-fi &&
+fi || die 'Concatenation failed'
 
 # Rewrite paths as needed
 
-while
-  IFS= read -r line
-do
-  case $line in
-    '' |\
-    '#'* |\
-    *': $'* ) echo "$line" ;;
-    *': '*)
-      s=${line#*': '}
-      t=${line%%': '*}
-      t=${t#././} t=${t#./}
+rewrite < "$output.7" > "$output.8" || die 'Rewriting failed'
 
-      x=$topdir$subdir
-      while
-	case $x///$s in
-	  *///./*) s=${s#./} ;;
-	  */.///*) x=${x%/.} ;;
-	  */..///*) false ;;
-	  */?*////../*) x=${x%/*/}/ s=${s#../} ;;
-	  *) false ;;
-	esac
-      do : ; done
+# Sort the entire output (this only makes a difference if incorporating the
+# original depfile rather than overwriting it.
 
-      printf '%s: %s\n' "$t" "$x$s"
-      ;;
-    * ) echo "$line"
-      echo >&2 'Warning: copying unmatched line: '"$line"
-      ;;
-  esac
-done < "$output.8" > "$output.9" &&
+if "$sort_depfile"
+then
+  sort -u "$output.8" > "$output.9"
+else
+  ln "$output.8" "$output.9"
+fi || die 'Sorting failed'
 
 # If everything has worked, replace the depfile
 
-mv "$output.9" "$depfile" &&
+mv "$output.9" "$depfile" || die 'Installation failed'
+
+# And then if requested, apply the patches to the Makefile
 
 if [ -n "$patch_makefile" ]
 then
@@ -325,9 +497,9 @@ then
     cat "$depfile"
   } > "$pmt" &&
   mv "$pmt" "$patch_makefile"
-fi &&
+fi || die 'Patching failed'
 
-cleanup &&
+end_cleanup
 
-exit 0
+exit
 }
