Make warnings during tests easier to read

diff --git a/tests/run-func b/tests/run-func
--- a/tests/run-func
+++ b/tests/run-func
@@ -1,5 +1,6 @@
 echo "warning: if you have exported functions defined in your environment," >&2
-echo "warning: they may show up as diff output." >&2
-echo "warning: if so, please do not consider this a test failure" >&2
+echo "         they may show up as ‘diff’ output." >&2
+echo "         if so, please do not consider this a test failure" >&2
+echo >&2
 ${THIS_SH} ./func.tests > ${BASH_TSTOUT} 2>&1
 diff ${BASH_TSTOUT} func.right && rm -f ${BASH_TSTOUT}
