Make warnings during tests easier to read

diff --git a/tests/run-trap b/tests/run-trap
--- a/tests/run-trap
+++ b/tests/run-trap
@@ -1,6 +1,7 @@
 echo "warning: UNIX versions number signals and schedule processes differently." >&2
-echo "warning: If output differing only in line numbers is produced, please" >&2
-echo "warning: do not consider this a test failure." >&2
+echo "         If output differing only in line numbers is produced, please" >&2
+echo "         do not consider this a test failure." >&2
+echo >&2
 
 ${THIS_SH} ./trap.tests > ${BASH_TSTOUT} 2>&1
 diff ${BASH_TSTOUT} trap.right && rm -f ${BASH_TSTOUT}
